### ISSUE TITLE
Screensaver not working properly on Vero4k (OSMC)

### ISSUE THREAD

**Issue by hissingshark** [popcornmix/screensaver.shadertoy#11]
Hi,

I've just migrated from an Rpi3 to a Vero4k running OSMC.
I've installed repository.popcornmix and screensaver.shadertoy from there.

Multiple shaders are having problems, either just appearing as a static screen, showing a visible jump as they loop or are confined to a corner of the screen.

Does this require a specific build for the Vero4k?

Thanks,

**Comment by popcornmix** [comment]
No special build is required. This build works on a number of arm platforms that support OpenGL ES2.
But the OpenGL ES2 drivers do vary with platfom. Some have limits in precision or complexity of shader it can handle that may be your issue.
I think you are better asking on http://discourse.osmc.tv.

**Comment by hissingshark** [comment]
If it's likely to be a driver issue then you're right of course, back to the platform is best.

Will do. And thanks for getting back to me.
